### ISSUE TITLE
Accept empty request bodies in POST requests

### ISSUE THREAD

**Issue by tiwillia** [openshift-online/uhc-cli#43]
POST endpoints that accept empty request bodies currently hang, for example:
```
$ uhc post /api/accounts_mgmt/v1/access_token
```

For this to work, the following is required:
```
$ echo "" | uhc post /api/accounts_mgmt/v1/access_token
```

**Comment by jhernand** [comment]
When you use one of this commands it will read the body from the standard input. So it will wait till it find the _EOF_. You can do that as you suggest or like this:

```
$ uhc post ... < /dev/null
```

Or this:

```
$ uhc post ... --body /dev/null
```

The CLI doesn't have intelligence enough to know that a particular request (like `/api/accounts_mgmt/v1/access_token`) requires an empty body.

What would you like the CLI to do in this case?

**Comment by tiwillia** [comment]
@jhernand if there is no way for the command to know that no input was provided, in case it is run as in my first example, then we can probably just close this. There are sufficient workarounds in place.

**Comment by jhernand** [comment]
OK. I am closing.
