### ISSUE TITLE
url param in the cli has become manditory

### ISSUE THREAD

**Issue by kbsingh** [openshift-online/uhc-cli#61]
It looks like the url param is now manditory, and we've lost the default. 

while I would perfer to retain the default, if we do want to drop it, lets ammend corrosponding docs in that case.

**Comment by jhernand** [comment]
In what command is the URL mandatory? Can you give an example?

**Comment by kbsingh** [comment]
$  uhc login --user something  --password something
Error: required flag(s) "url" not set

**Comment by jhernand** [comment]
This was fixed in #63 and included in release [0.1.19](https://github.com/openshift-online/uhc-cli/releases/tag/v0.1.19).
